apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/kosta/ticketing/db"
